backend:
  name: github
  repo: theforktreeproject/theforktreeproject.com
  branch: main

media_folder: public/images/journal
public_folder: /images/journal

collections:
  - name: blog
    label: Blog
    folder: src/content/journal
    create: true
    slug: "{{slug}}"
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: Author, name: author, widget: string, default: "Elizabeth Jarvis" }
      - { label: Featured Image, name: image, widget: image, required: false }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Body, name: body, widget: markdown }
