// Auto-generated by scripts/generate-journal-thumbnails.mjs. Do not edit manually.

export type JournalThumbnail = {
  src: string;
  srcset: string;
  width: number;
  height: number;
};

export const journalThumbnails = {
  "/images/journal/a-job-well-done.jpg": {
    "src": "/images/journal/thumbnails/a-job-well-done-5c3c6549-800.webp",
    "srcset": "/images/journal/thumbnails/a-job-well-done-5c3c6549-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/a-second-generation.jpg": {
    "src": "/images/journal/thumbnails/a-second-generation-6eb285cd-800.webp",
    "srcset": "/images/journal/thumbnails/a-second-generation-6eb285cd-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/all-the-best-jobs.jpg": {
    "src": "/images/journal/thumbnails/all-the-best-jobs-1b54c2e8-800.webp",
    "srcset": "/images/journal/thumbnails/all-the-best-jobs-1b54c2e8-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/ancient-wisdom-modern-action.jpg": {
    "src": "/images/journal/thumbnails/ancient-wisdom-modern-action-95976752-800.webp",
    "srcset": "/images/journal/thumbnails/ancient-wisdom-modern-action-95976752-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/and-its-a-wrap.jpg": {
    "src": "/images/journal/thumbnails/and-its-a-wrap-89ada63b-800.webp",
    "srcset": "/images/journal/thumbnails/and-its-a-wrap-89ada63b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/and-then-there-was-none.jpg": {
    "src": "/images/journal/thumbnails/and-then-there-was-none-13ca287a-800.webp",
    "srcset": "/images/journal/thumbnails/and-then-there-was-none-13ca287a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/annesley-junior-school-returns-to-forktree.jpg": {
    "src": "/images/journal/thumbnails/annesley-junior-school-returns-to-forktree-b38581f7-800.webp",
    "srcset": "/images/journal/thumbnails/annesley-junior-school-returns-to-forktree-b38581f7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/annesley-junior-school-visit-to-forktree.jpg": {
    "src": "/images/journal/thumbnails/annesley-junior-school-visit-to-forktree-c84e2554-800.webp",
    "srcset": "/images/journal/thumbnails/annesley-junior-school-visit-to-forktree-c84e2554-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/another-rare-species-recorded-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/another-rare-species-recorded-at-forktree-33211a52-800.webp",
    "srcset": "/images/journal/thumbnails/another-rare-species-recorded-at-forktree-33211a52-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/at-the-starting-block.jpg": {
    "src": "/images/journal/thumbnails/at-the-starting-block-cfc29ec7-800.webp",
    "srcset": "/images/journal/thumbnails/at-the-starting-block-cfc29ec7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/back-to-school.jpeg": {
    "src": "/images/journal/thumbnails/back-to-school-c9187cab-800.webp",
    "srcset": "/images/journal/thumbnails/back-to-school-c9187cab-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/beacons-of-hope.jpg": {
    "src": "/images/journal/thumbnails/beacons-of-hope-1002fcf4-800.webp",
    "srcset": "/images/journal/thumbnails/beacons-of-hope-1002fcf4-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/beginnings.jpg": {
    "src": "/images/journal/thumbnails/beginnings-573ac88a-800.webp",
    "srcset": "/images/journal/thumbnails/beginnings-573ac88a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/blackwood-high-outdoor-ed-superstars-think-global-and-act-local.jpg": {
    "src": "/images/journal/thumbnails/blackwood-high-outdoor-ed-superstars-think-global-and-act-local-bdce8185-800.webp",
    "srcset": "/images/journal/thumbnails/blackwood-high-outdoor-ed-superstars-think-global-and-act-local-bdce8185-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/blaze-of-glory.jpg": {
    "src": "/images/journal/thumbnails/blaze-of-glory-2fbbce30-800.webp",
    "srcset": "/images/journal/thumbnails/blaze-of-glory-2fbbce30-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/breaking-down-barriers.jpg": {
    "src": "/images/journal/thumbnails/breaking-down-barriers-70a4e28d-800.webp",
    "srcset": "/images/journal/thumbnails/breaking-down-barriers-70a4e28d-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/bring-back-the-glossies.jpg": {
    "src": "/images/journal/thumbnails/bring-back-the-glossies-b4204ff7-800.webp",
    "srcset": "/images/journal/thumbnails/bring-back-the-glossies-b4204ff7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/building-blocks.jpg": {
    "src": "/images/journal/thumbnails/building-blocks-aa3db459-800.webp",
    "srcset": "/images/journal/thumbnails/building-blocks-aa3db459-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/calling-all-volunteers.jpg": {
    "src": "/images/journal/thumbnails/calling-all-volunteers-2b4a2546-800.webp",
    "srcset": "/images/journal/thumbnails/calling-all-volunteers-2b4a2546-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/camping-canvas.jpg": {
    "src": "/images/journal/thumbnails/camping-canvas-25788eca-800.webp",
    "srcset": "/images/journal/thumbnails/camping-canvas-25788eca-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/caterpillar-return.jpg": {
    "src": "/images/journal/thumbnails/caterpillar-return-0236a65b-800.webp",
    "srcset": "/images/journal/thumbnails/caterpillar-return-0236a65b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/celebrating-our-volunteers-in-national-volunteers-week.jpg": {
    "src": "/images/journal/thumbnails/celebrating-our-volunteers-in-national-volunteers-week-b94786f9-800.webp",
    "srcset": "/images/journal/thumbnails/celebrating-our-volunteers-in-national-volunteers-week-b94786f9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/celebrating-world-environment-day-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/celebrating-world-environment-day-at-forktree-e2d7e4b1-800.webp",
    "srcset": "/images/journal/thumbnails/celebrating-world-environment-day-at-forktree-e2d7e4b1-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/change-makers-celebrating-our-volunteers.jpg": {
    "src": "/images/journal/thumbnails/change-makers-celebrating-our-volunteers-4572e025-800.webp",
    "srcset": "/images/journal/thumbnails/change-makers-celebrating-our-volunteers-4572e025-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/chu-support-for-forktree.png": {
    "src": "/images/journal/thumbnails/chu-support-for-forktree-686f2d08-800.webp",
    "srcset": "/images/journal/thumbnails/chu-support-for-forktree-686f2d08-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/chu-volunteers-return-to-forktree.jpg": {
    "src": "/images/journal/thumbnails/chu-volunteers-return-to-forktree-f0237205-800.webp",
    "srcset": "/images/journal/thumbnails/chu-volunteers-return-to-forktree-f0237205-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/circular-economy-in-action-with-pac.jpg": {
    "src": "/images/journal/thumbnails/circular-economy-in-action-with-pac-de872afb-800.webp",
    "srcset": "/images/journal/thumbnails/circular-economy-in-action-with-pac-de872afb-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/clean-up-australia-day.jpg": {
    "src": "/images/journal/thumbnails/clean-up-australia-day-dd9f5b08-800.webp",
    "srcset": "/images/journal/thumbnails/clean-up-australia-day-dd9f5b08-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/collaboration-with-princes-trust-australia.jpeg": {
    "src": "/images/journal/thumbnails/collaboration-with-princes-trust-australia-7ff01d57-800.webp",
    "srcset": "/images/journal/thumbnails/collaboration-with-princes-trust-australia-7ff01d57-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/completing-the-circular-economy-loop.jpg": {
    "src": "/images/journal/thumbnails/completing-the-circular-economy-loop-20c7659e-800.webp",
    "srcset": "/images/journal/thumbnails/completing-the-circular-economy-loop-20c7659e-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/creative-design-from-tanks-to-beds.jpg": {
    "src": "/images/journal/thumbnails/creative-design-from-tanks-to-beds-dce00f89-800.webp",
    "srcset": "/images/journal/thumbnails/creative-design-from-tanks-to-beds-dce00f89-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/crows-kick-goals-for-biodiversity.jpg": {
    "src": "/images/journal/thumbnails/crows-kick-goals-for-biodiversity-d351bc0b-800.webp",
    "srcset": "/images/journal/thumbnails/crows-kick-goals-for-biodiversity-d351bc0b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/deloitte-taskforce.jpg": {
    "src": "/images/journal/thumbnails/deloitte-taskforce-79e9c81c-800.webp",
    "srcset": "/images/journal/thumbnails/deloitte-taskforce-79e9c81c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/digging-deep-for-doing-good.jpg": {
    "src": "/images/journal/thumbnails/digging-deep-for-doing-good-d275515b-800.webp",
    "srcset": "/images/journal/thumbnails/digging-deep-for-doing-good-d275515b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/ecological-makeover-yankalilla-regional-news.jpg": {
    "src": "/images/journal/thumbnails/ecological-makeover-yankalilla-regional-news-4bb81950-800.webp",
    "srcset": "/images/journal/thumbnails/ecological-makeover-yankalilla-regional-news-4bb81950-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/elegant-parrots-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/elegant-parrots-at-forktree-b861489a-800.webp",
    "srcset": "/images/journal/thumbnails/elegant-parrots-at-forktree-b861489a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/endorsement-from-sa-minister-for-environment-and-water.jpg": {
    "src": "/images/journal/thumbnails/endorsement-from-sa-minister-for-environment-and-water-151b3222-800.webp",
    "srcset": "/images/journal/thumbnails/endorsement-from-sa-minister-for-environment-and-water-151b3222-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/engineers-without-borders-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/engineers-without-borders-at-forktree-cddafefb-800.webp",
    "srcset": "/images/journal/thumbnails/engineers-without-borders-at-forktree-cddafefb-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/environmental-stewards-of-the-future.jpg": {
    "src": "/images/journal/thumbnails/environmental-stewards-of-the-future-60655a5a-800.webp",
    "srcset": "/images/journal/thumbnails/environmental-stewards-of-the-future-60655a5a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/every-cloud.jpg": {
    "src": "/images/journal/thumbnails/every-cloud-b289beed-800.webp",
    "srcset": "/images/journal/thumbnails/every-cloud-b289beed-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/excavators-spades-and-rakes.jpg": {
    "src": "/images/journal/thumbnails/excavators-spades-and-rakes-2c22721f-800.webp",
    "srcset": "/images/journal/thumbnails/excavators-spades-and-rakes-2c22721f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/exit-strategy.jpg": {
    "src": "/images/journal/thumbnails/exit-strategy-93511247-800.webp",
    "srcset": "/images/journal/thumbnails/exit-strategy-93511247-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/feelinggood.jpg": {
    "src": "/images/journal/thumbnails/feelinggood-5f262a16-800.webp",
    "srcset": "/images/journal/thumbnails/feelinggood-5f262a16-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/fencing-challenges.jpg": {
    "src": "/images/journal/thumbnails/fencing-challenges-3b7653b0-800.webp",
    "srcset": "/images/journal/thumbnails/fencing-challenges-3b7653b0-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/fifty-sa-article-on-tim-jarvis-and-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/fifty-sa-article-on-tim-jarvis-and-the-forktree-project-ba9540cd-800.webp",
    "srcset": "/images/journal/thumbnails/fifty-sa-article-on-tim-jarvis-and-the-forktree-project-ba9540cd-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/first-batch-of-saplings-make-their-way-to-forktree.jpg": {
    "src": "/images/journal/thumbnails/first-batch-of-saplings-make-their-way-to-forktree-dc8b48d1-800.webp",
    "srcset": "/images/journal/thumbnails/first-batch-of-saplings-make-their-way-to-forktree-dc8b48d1-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/first-saplings-in-position.jpg": {
    "src": "/images/journal/thumbnails/first-saplings-in-position-d90b56e9-800.webp",
    "srcset": "/images/journal/thumbnails/first-saplings-in-position-d90b56e9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/first-steps.jpg": {
    "src": "/images/journal/thumbnails/first-steps-091fe994-800.webp",
    "srcset": "/images/journal/thumbnails/first-steps-091fe994-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/fleurieu-fog.jpg": {
    "src": "/images/journal/thumbnails/fleurieu-fog-d1649600-800.webp",
    "srcset": "/images/journal/thumbnails/fleurieu-fog-d1649600-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/food-for-the-future.jpg": {
    "src": "/images/journal/thumbnails/food-for-the-future-316523a2-800.webp",
    "srcset": "/images/journal/thumbnails/food-for-the-future-316523a2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/forktree-fridays.jpg": {
    "src": "/images/journal/thumbnails/forktree-fridays-eb348e6b-800.webp",
    "srcset": "/images/journal/thumbnails/forktree-fridays-eb348e6b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/forktree-project-granted-charity-status.jpg": {
    "src": "/images/journal/thumbnails/forktree-project-granted-charity-status-70051b59-800.webp",
    "srcset": "/images/journal/thumbnails/forktree-project-granted-charity-status-70051b59-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/forktree-project-open-day-october-2024.jpg": {
    "src": "/images/journal/thumbnails/forktree-project-open-day-october-2024-1102a0e9-800.webp",
    "srcset": "/images/journal/thumbnails/forktree-project-open-day-october-2024-1102a0e9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/forktree-the-festival-of-nature.jpg": {
    "src": "/images/journal/thumbnails/forktree-the-festival-of-nature-6dc01970-800.webp",
    "srcset": "/images/journal/thumbnails/forktree-the-festival-of-nature-6dc01970-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/forktrees-40th-lepidoptera-species.jpg": {
    "src": "/images/journal/thumbnails/forktrees-40th-lepidoptera-species-9a582503-800.webp",
    "srcset": "/images/journal/thumbnails/forktrees-40th-lepidoptera-species-9a582503-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/forktrees-first-threatened-bird-species.jpg": {
    "src": "/images/journal/thumbnails/forktrees-first-threatened-bird-species-da177a65-800.webp",
    "srcset": "/images/journal/thumbnails/forktrees-first-threatened-bird-species-da177a65-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/four-steps-to-victory.jpg": {
    "src": "/images/journal/thumbnails/four-steps-to-victory-8f1bba0f-800.webp",
    "srcset": "/images/journal/thumbnails/four-steps-to-victory-8f1bba0f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/friends-of-forktree-planting-day-2024.jpg": {
    "src": "/images/journal/thumbnails/friends-of-forktree-planting-day-2024-9cffc960-800.webp",
    "srcset": "/images/journal/thumbnails/friends-of-forktree-planting-day-2024-9cffc960-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/friends-of-forktree-planting-day-2025.jpg": {
    "src": "/images/journal/thumbnails/friends-of-forktree-planting-day-2025-7236944d-800.webp",
    "srcset": "/images/journal/thumbnails/friends-of-forktree-planting-day-2025-7236944d-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/friends-of-forktree-planting-day-for-national-tree-day.jpg": {
    "src": "/images/journal/thumbnails/friends-of-forktree-planting-day-for-national-tree-day-21d2bc00-800.webp",
    "srcset": "/images/journal/thumbnails/friends-of-forktree-planting-day-for-national-tree-day-21d2bc00-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/from-big-things-little-things-grow.jpg": {
    "src": "/images/journal/thumbnails/from-big-things-little-things-grow-5c1eb6a2-800.webp",
    "srcset": "/images/journal/thumbnails/from-big-things-little-things-grow-5c1eb6a2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/from-rubble-pile-to-kitchen-pride.jpg": {
    "src": "/images/journal/thumbnails/from-rubble-pile-to-kitchen-pride-59016687-800.webp",
    "srcset": "/images/journal/thumbnails/from-rubble-pile-to-kitchen-pride-59016687-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/from-rubble-to-tracks.jpg": {
    "src": "/images/journal/thumbnails/from-rubble-to-tracks-d80e4f4c-800.webp",
    "srcset": "/images/journal/thumbnails/from-rubble-to-tracks-d80e4f4c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/gathering-seed.jpg": {
    "src": "/images/journal/thumbnails/gathering-seed-97940adb-800.webp",
    "srcset": "/images/journal/thumbnails/gathering-seed-97940adb-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/get-set.jpg": {
    "src": "/images/journal/thumbnails/get-set-e1259e01-800.webp",
    "srcset": "/images/journal/thumbnails/get-set-e1259e01-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/getting-ready.jpg": {
    "src": "/images/journal/thumbnails/getting-ready-c88a36bc-800.webp",
    "srcset": "/images/journal/thumbnails/getting-ready-c88a36bc-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/go-1.jpg": {
    "src": "/images/journal/thumbnails/go-1-948e0ab7-800.webp",
    "srcset": "/images/journal/thumbnails/go-1-948e0ab7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/grand-designs.jpg": {
    "src": "/images/journal/thumbnails/grand-designs-aaef2eea-800.webp",
    "srcset": "/images/journal/thumbnails/grand-designs-aaef2eea-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/grass-seed-harvest.jpg": {
    "src": "/images/journal/thumbnails/grass-seed-harvest-7c53b866-800.webp",
    "srcset": "/images/journal/thumbnails/grass-seed-harvest-7c53b866-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/great-wall-of-forktree.jpg": {
    "src": "/images/journal/thumbnails/great-wall-of-forktree-67c4687a-800.webp",
    "srcset": "/images/journal/thumbnails/great-wall-of-forktree-67c4687a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/green-facilities.jpg": {
    "src": "/images/journal/thumbnails/green-facilities-10286a61-800.webp",
    "srcset": "/images/journal/thumbnails/green-facilities-10286a61-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/green-shoots-of-recovery.jpg": {
    "src": "/images/journal/thumbnails/green-shoots-of-recovery-c9ff71d4-800.webp",
    "srcset": "/images/journal/thumbnails/green-shoots-of-recovery-c9ff71d4-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/greenhouse-effect.jpg": {
    "src": "/images/journal/thumbnails/greenhouse-effect-437602b1-800.webp",
    "srcset": "/images/journal/thumbnails/greenhouse-effect-437602b1-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/growing-an-inclusive-space.jpg": {
    "src": "/images/journal/thumbnails/growing-an-inclusive-space-b0c7a5f2-800.webp",
    "srcset": "/images/journal/thumbnails/growing-an-inclusive-space-b0c7a5f2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/growth-spurt.jpg": {
    "src": "/images/journal/thumbnails/growth-spurt-fa8b6b9f-800.webp",
    "srcset": "/images/journal/thumbnails/growth-spurt-fa8b6b9f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/hakea-moth.jpg": {
    "src": "/images/journal/thumbnails/hakea-moth-23fb35eb-800.webp",
    "srcset": "/images/journal/thumbnails/hakea-moth-23fb35eb-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/hard-yacca.jpg": {
    "src": "/images/journal/thumbnails/hard-yacca-4a164978-800.webp",
    "srcset": "/images/journal/thumbnails/hard-yacca-4a164978-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/harnessing-solar-power.jpg": {
    "src": "/images/journal/thumbnails/harnessing-solar-power-5647f0a5-800.webp",
    "srcset": "/images/journal/thumbnails/harnessing-solar-power-5647f0a5-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/helping-hands.jpeg": {
    "src": "/images/journal/thumbnails/helping-hands-514212cf-800.webp",
    "srcset": "/images/journal/thumbnails/helping-hands-514212cf-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/hempcrete-magic.jpg": {
    "src": "/images/journal/thumbnails/hempcrete-magic-1738101b-800.webp",
    "srcset": "/images/journal/thumbnails/hempcrete-magic-1738101b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/hi-tech-solutions-for-water-management.jpg": {
    "src": "/images/journal/thumbnails/hi-tech-solutions-for-water-management-aedfbf77-800.webp",
    "srcset": "/images/journal/thumbnails/hi-tech-solutions-for-water-management-aedfbf77-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/high-rise-hollows.jpg": {
    "src": "/images/journal/thumbnails/high-rise-hollows-657679e3-800.webp",
    "srcset": "/images/journal/thumbnails/high-rise-hollows-657679e3-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/hotels-for-trees-at-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/hotels-for-trees-at-the-forktree-project-cb83e51d-800.webp",
    "srcset": "/images/journal/thumbnails/hotels-for-trees-at-the-forktree-project-cb83e51d-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/improving-water-efficiency-step-by-step.jpg": {
    "src": "/images/journal/thumbnails/improving-water-efficiency-step-by-step-f8cf5537-800.webp",
    "srcset": "/images/journal/thumbnails/improving-water-efficiency-step-by-step-f8cf5537-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/innovate-to-create.jpg": {
    "src": "/images/journal/thumbnails/innovate-to-create-b3e1a6d6-800.webp",
    "srcset": "/images/journal/thumbnails/innovate-to-create-b3e1a6d6-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/its-a-long-way-to-the-top-of-the-hill.jpg": {
    "src": "/images/journal/thumbnails/its-a-long-way-to-the-top-of-the-hill-21253cfa-800.webp",
    "srcset": "/images/journal/thumbnails/its-a-long-way-to-the-top-of-the-hill-21253cfa-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/its-a-newday.jpg": {
    "src": "/images/journal/thumbnails/its-a-newday-e103b304-800.webp",
    "srcset": "/images/journal/thumbnails/its-a-newday-e103b304-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/its-got-to-go.jpg": {
    "src": "/images/journal/thumbnails/its-got-to-go-5dfec38a-800.webp",
    "srcset": "/images/journal/thumbnails/its-got-to-go-5dfec38a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/jarvis-i-need-more-power.jpeg": {
    "src": "/images/journal/thumbnails/jarvis-i-need-more-power-fc7af9c7-800.webp",
    "srcset": "/images/journal/thumbnails/jarvis-i-need-more-power-fc7af9c7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/kicking-goals-with-kesab.jpg": {
    "src": "/images/journal/thumbnails/kicking-goals-with-kesab-12e24a67-800.webp",
    "srcset": "/images/journal/thumbnails/kicking-goals-with-kesab-12e24a67-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/land-of-the-giants.jpg": {
    "src": "/images/journal/thumbnails/land-of-the-giants-4964ce89-800.webp",
    "srcset": "/images/journal/thumbnails/land-of-the-giants-4964ce89-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/laying-the-foundations-of-forktree.jpg": {
    "src": "/images/journal/thumbnails/laying-the-foundations-of-forktree-c27ab05f-800.webp",
    "srcset": "/images/journal/thumbnails/laying-the-foundations-of-forktree-c27ab05f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/laying-the-foundations.jpg": {
    "src": "/images/journal/thumbnails/laying-the-foundations-51105e30-800.webp",
    "srcset": "/images/journal/thumbnails/laying-the-foundations-51105e30-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/lesser-wanderer.jpg": {
    "src": "/images/journal/thumbnails/lesser-wanderer-a2f3f86c-800.webp",
    "srcset": "/images/journal/thumbnails/lesser-wanderer-a2f3f86c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/let-planting-season-commence.jpg": {
    "src": "/images/journal/thumbnails/let-planting-season-commence-cee4cc71-800.webp",
    "srcset": "/images/journal/thumbnails/let-planting-season-commence-cee4cc71-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/like-a-phoenix-from-the-ashes.jpg": {
    "src": "/images/journal/thumbnails/like-a-phoenix-from-the-ashes-2b511893-800.webp",
    "srcset": "/images/journal/thumbnails/like-a-phoenix-from-the-ashes-2b511893-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/making-the-bed.jpg": {
    "src": "/images/journal/thumbnails/making-the-bed-c2cf1867-800.webp",
    "srcset": "/images/journal/thumbnails/making-the-bed-c2cf1867-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/manna-from-heaven.jpg": {
    "src": "/images/journal/thumbnails/manna-from-heaven-b59884a4-800.webp",
    "srcset": "/images/journal/thumbnails/manna-from-heaven-b59884a4-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/many-hands-make-light-work.jpg": {
    "src": "/images/journal/thumbnails/many-hands-make-light-work-e75b258b-800.webp",
    "srcset": "/images/journal/thumbnails/many-hands-make-light-work-e75b258b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/maths-for-real-life.jpg": {
    "src": "/images/journal/thumbnails/maths-for-real-life-054aa4b8-800.webp",
    "srcset": "/images/journal/thumbnails/maths-for-real-life-054aa4b8-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/mobile-watering.jpg": {
    "src": "/images/journal/thumbnails/mobile-watering-55d5812f-800.webp",
    "srcset": "/images/journal/thumbnails/mobile-watering-55d5812f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/national-recycling-week-the-forktree-project-.jpg": {
    "src": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-4f4114ce-800.webp",
    "srcset": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-4f4114ce-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/national-recycling-week-the-forktree-project-1.jpg": {
    "src": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-1-46fe59d6-800.webp",
    "srcset": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-1-46fe59d6-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/national-recycling-week-the-forktree-project-2.jpg": {
    "src": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-2-9b915043-800.webp",
    "srcset": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-2-9b915043-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/national-recycling-week-the-forktree-project-3.jpg": {
    "src": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-3-57e370e2-800.webp",
    "srcset": "/images/journal/thumbnails/national-recycling-week-the-forktree-project-3-57e370e2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/national-tree-day-at-the-forktree-project.jpeg": {
    "src": "/images/journal/thumbnails/national-tree-day-at-the-forktree-project-c7bbf817-800.webp",
    "srcset": "/images/journal/thumbnails/national-tree-day-at-the-forktree-project-c7bbf817-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/native-grass-generation-game.jpg": {
    "src": "/images/journal/thumbnails/native-grass-generation-game-2a814e6f-800.webp",
    "srcset": "/images/journal/thumbnails/native-grass-generation-game-2a814e6f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/nature-play-sa-and-hallett-cove-south-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/nature-play-sa-and-hallett-cove-south-at-forktree-9acfac18-800.webp",
    "srcset": "/images/journal/thumbnails/nature-play-sa-and-hallett-cove-south-at-forktree-9acfac18-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/nature-play-sa-at-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/nature-play-sa-at-the-forktree-project-2e15b735-800.webp",
    "srcset": "/images/journal/thumbnails/nature-play-sa-at-the-forktree-project-2e15b735-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/nest-building.jpg": {
    "src": "/images/journal/thumbnails/nest-building-e3908c8b-800.webp",
    "srcset": "/images/journal/thumbnails/nest-building-e3908c8b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/new-friends-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/new-friends-at-forktree-75a4213c-800.webp",
    "srcset": "/images/journal/thumbnails/new-friends-at-forktree-75a4213c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/newday-leadership-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/newday-leadership-at-forktree-3fa951ce-800.webp",
    "srcset": "/images/journal/thumbnails/newday-leadership-at-forktree-3fa951ce-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/newday-returns-to-forktree.jpg": {
    "src": "/images/journal/thumbnails/newday-returns-to-forktree-c38822ef-800.webp",
    "srcset": "/images/journal/thumbnails/newday-returns-to-forktree-c38822ef-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/nursery-taking-shape.jpg": {
    "src": "/images/journal/thumbnails/nursery-taking-shape-cd017594-800.webp",
    "srcset": "/images/journal/thumbnails/nursery-taking-shape-cd017594-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/nursery-update.jpg": {
    "src": "/images/journal/thumbnails/nursery-update-be7670af-800.webp",
    "srcset": "/images/journal/thumbnails/nursery-update-be7670af-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/old-planks-given-new-life.jpg": {
    "src": "/images/journal/thumbnails/old-planks-given-new-life-1dd803c3-800.webp",
    "srcset": "/images/journal/thumbnails/old-planks-given-new-life-1dd803c3-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/olive-eradication.jpg": {
    "src": "/images/journal/thumbnails/olive-eradication-22f5e663-800.webp",
    "srcset": "/images/journal/thumbnails/olive-eradication-22f5e663-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/on-your-marks.jpg": {
    "src": "/images/journal/thumbnails/on-your-marks-fc9aa4ef-800.webp",
    "srcset": "/images/journal/thumbnails/on-your-marks-fc9aa4ef-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/operation-flinders-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/operation-flinders-the-forktree-project-8220724a-800.webp",
    "srcset": "/images/journal/thumbnails/operation-flinders-the-forktree-project-8220724a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/parched.jpg": {
    "src": "/images/journal/thumbnails/parched-4999e22a-800.webp",
    "srcset": "/images/journal/thumbnails/parched-4999e22a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/party-trick.jpg": {
    "src": "/images/journal/thumbnails/party-trick-b3c724be-800.webp",
    "srcset": "/images/journal/thumbnails/party-trick-b3c724be-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/perfecting-the-prototype.jpg": {
    "src": "/images/journal/thumbnails/perfecting-the-prototype-384e2922-800.webp",
    "srcset": "/images/journal/thumbnails/perfecting-the-prototype-384e2922-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/pipe-dream.jpeg": {
    "src": "/images/journal/thumbnails/pipe-dream-b03340b9-800.webp",
    "srcset": "/images/journal/thumbnails/pipe-dream-b03340b9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/pizza-base.jpeg": {
    "src": "/images/journal/thumbnails/pizza-base-4b5664e4-800.webp",
    "srcset": "/images/journal/thumbnails/pizza-base-4b5664e4-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/planting-prep-1.jpg": {
    "src": "/images/journal/thumbnails/planting-prep-1-fa0a9008-800.webp",
    "srcset": "/images/journal/thumbnails/planting-prep-1-fa0a9008-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/planting-prep.jpg": {
    "src": "/images/journal/thumbnails/planting-prep-64b83ba9-800.webp",
    "srcset": "/images/journal/thumbnails/planting-prep-64b83ba9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/potential.jpg": {
    "src": "/images/journal/thumbnails/potential-e686c30d-800.webp",
    "srcset": "/images/journal/thumbnails/potential-e686c30d-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/power-planting-with-conservation-volunteers-australia.jpg": {
    "src": "/images/journal/thumbnails/power-planting-with-conservation-volunteers-australia-0a410563-800.webp",
    "srcset": "/images/journal/thumbnails/power-planting-with-conservation-volunteers-australia-0a410563-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/precious-jewels.jpg": {
    "src": "/images/journal/thumbnails/precious-jewels-4b53f7a8-800.webp",
    "srcset": "/images/journal/thumbnails/precious-jewels-4b53f7a8-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/preparing-to-plant-the-first-gully.jpg": {
    "src": "/images/journal/thumbnails/preparing-to-plant-the-first-gully-9ca45c74-800.webp",
    "srcset": "/images/journal/thumbnails/preparing-to-plant-the-first-gully-9ca45c74-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/prepping-the-next-phase.jpg": {
    "src": "/images/journal/thumbnails/prepping-the-next-phase-5dc01c16-800.webp",
    "srcset": "/images/journal/thumbnails/prepping-the-next-phase-5dc01c16-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/priming-the-canvas.jpg": {
    "src": "/images/journal/thumbnails/priming-the-canvas-9a67927b-800.webp",
    "srcset": "/images/journal/thumbnails/priming-the-canvas-9a67927b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/purge-on-plastics.jpg": {
    "src": "/images/journal/thumbnails/purge-on-plastics-77b407b1-800.webp",
    "srcset": "/images/journal/thumbnails/purge-on-plastics-77b407b1-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/rainbow-magic-returns.jpg": {
    "src": "/images/journal/thumbnails/rainbow-magic-returns-43835996-800.webp",
    "srcset": "/images/journal/thumbnails/rainbow-magic-returns-43835996-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/rainbow-magic.jpg": {
    "src": "/images/journal/thumbnails/rainbow-magic-ed378b95-800.webp",
    "srcset": "/images/journal/thumbnails/rainbow-magic-ed378b95-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/rare-chequered-copper-butterfly-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/rare-chequered-copper-butterfly-at-forktree-17041b9a-800.webp",
    "srcset": "/images/journal/thumbnails/rare-chequered-copper-butterfly-at-forktree-17041b9a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/rare-seed-orchard-update.jpg": {
    "src": "/images/journal/thumbnails/rare-seed-orchard-update-90a922d0-800.webp",
    "srcset": "/images/journal/thumbnails/rare-seed-orchard-update-90a922d0-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/recycle-and-reuse.jpg": {
    "src": "/images/journal/thumbnails/recycle-and-reuse-6fa46a69-800.webp",
    "srcset": "/images/journal/thumbnails/recycle-and-reuse-6fa46a69-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/reflections-on-the-bushfires.jpg": {
    "src": "/images/journal/thumbnails/reflections-on-the-bushfires-c803bb51-800.webp",
    "srcset": "/images/journal/thumbnails/reflections-on-the-bushfires-c803bb51-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/regenerative-design-on-earth-overshoot-day.jpg": {
    "src": "/images/journal/thumbnails/regenerative-design-on-earth-overshoot-day-1c33df26-800.webp",
    "srcset": "/images/journal/thumbnails/regenerative-design-on-earth-overshoot-day-1c33df26-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/remarkable-resilience.jpg": {
    "src": "/images/journal/thumbnails/remarkable-resilience-065d1559-800.webp",
    "srcset": "/images/journal/thumbnails/remarkable-resilience-065d1559-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/repelling-invaders.jpg": {
    "src": "/images/journal/thumbnails/repelling-invaders-d7ad765b-800.webp",
    "srcset": "/images/journal/thumbnails/repelling-invaders-d7ad765b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/ripe.jpg": {
    "src": "/images/journal/thumbnails/ripe-29b59d00-800.webp",
    "srcset": "/images/journal/thumbnails/ripe-29b59d00-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/role-models-in-the-field.jpg": {
    "src": "/images/journal/thumbnails/role-models-in-the-field-5c292ef7-800.webp",
    "srcset": "/images/journal/thumbnails/role-models-in-the-field-5c292ef7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/roo-challenges.jpg": {
    "src": "/images/journal/thumbnails/roo-challenges-a69bf141-800.webp",
    "srcset": "/images/journal/thumbnails/roo-challenges-a69bf141-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/roo-proof-fence.jpg": {
    "src": "/images/journal/thumbnails/roo-proof-fence-dd55cecf-800.webp",
    "srcset": "/images/journal/thumbnails/roo-proof-fence-dd55cecf-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/rubble-rubble-toil-and-trouble.jpg": {
    "src": "/images/journal/thumbnails/rubble-rubble-toil-and-trouble-ffe3228a-800.webp",
    "srcset": "/images/journal/thumbnails/rubble-rubble-toil-and-trouble-ffe3228a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/rubble-update.jpg": {
    "src": "/images/journal/thumbnails/rubble-update-e5c17025-800.webp",
    "srcset": "/images/journal/thumbnails/rubble-update-e5c17025-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/second-life.jpg": {
    "src": "/images/journal/thumbnails/second-life-e5121b3c-800.webp",
    "srcset": "/images/journal/thumbnails/second-life-e5121b3c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/seed-cleaning.jpg": {
    "src": "/images/journal/thumbnails/seed-cleaning-087d7fe3-800.webp",
    "srcset": "/images/journal/thumbnails/seed-cleaning-087d7fe3-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/seed-orchard-reticulation.jpg": {
    "src": "/images/journal/thumbnails/seed-orchard-reticulation-b6b875f7-800.webp",
    "srcset": "/images/journal/thumbnails/seed-orchard-reticulation-b6b875f7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/seeding-frenzy.jpg": {
    "src": "/images/journal/thumbnails/seeding-frenzy-9d709ba3-800.webp",
    "srcset": "/images/journal/thumbnails/seeding-frenzy-9d709ba3-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/seeds-of-hope-1.jpg": {
    "src": "/images/journal/thumbnails/seeds-of-hope-1-8a7d3211-800.webp",
    "srcset": "/images/journal/thumbnails/seeds-of-hope-1-8a7d3211-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/seeds-of-hope.jpg": {
    "src": "/images/journal/thumbnails/seeds-of-hope-c3c275cd-800.webp",
    "srcset": "/images/journal/thumbnails/seeds-of-hope-c3c275cd-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/signs-of-the-past.jpg": {
    "src": "/images/journal/thumbnails/signs-of-the-past-e861c8ec-800.webp",
    "srcset": "/images/journal/thumbnails/signs-of-the-past-e861c8ec-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/slope-stabilisation-with-native-plants.jpg": {
    "src": "/images/journal/thumbnails/slope-stabilisation-with-native-plants-3683ffd2-800.webp",
    "srcset": "/images/journal/thumbnails/slope-stabilisation-with-native-plants-3683ffd2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/smashing-climate-action.jpg": {
    "src": "/images/journal/thumbnails/smashing-climate-action-a311fafc-800.webp",
    "srcset": "/images/journal/thumbnails/smashing-climate-action-a311fafc-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/soil-testing.jpg": {
    "src": "/images/journal/thumbnails/soil-testing-876be3ff-800.webp",
    "srcset": "/images/journal/thumbnails/soil-testing-876be3ff-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/sowing-seed.jpg": {
    "src": "/images/journal/thumbnails/sowing-seed-40c5e9ad-800.webp",
    "srcset": "/images/journal/thumbnails/sowing-seed-40c5e9ad-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/sowing-the-seeds-of-change.jpeg": {
    "src": "/images/journal/thumbnails/sowing-the-seeds-of-change-d30f5473-800.webp",
    "srcset": "/images/journal/thumbnails/sowing-the-seeds-of-change-d30f5473-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/spring-has-sprung.jpg": {
    "src": "/images/journal/thumbnails/spring-has-sprung-7f4d7b33-800.webp",
    "srcset": "/images/journal/thumbnails/spring-has-sprung-7f4d7b33-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/stage-2-geography-and-outdoor-ed-camp-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/stage-2-geography-and-outdoor-ed-camp-at-forktree-01bd0400-800.webp",
    "srcset": "/images/journal/thumbnails/stage-2-geography-and-outdoor-ed-camp-at-forktree-01bd0400-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/stake-remake-bringing-planting-and-recycling-together.jpg": {
    "src": "/images/journal/thumbnails/stake-remake-bringing-planting-and-recycling-together-7ee9bdc3-800.webp",
    "srcset": "/images/journal/thumbnails/stake-remake-bringing-planting-and-recycling-together-7ee9bdc3-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/star-party.jpg": {
    "src": "/images/journal/thumbnails/star-party-988f64c5-800.webp",
    "srcset": "/images/journal/thumbnails/star-party-988f64c5-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/string-theory.jpg": {
    "src": "/images/journal/thumbnails/string-theory-30cf6272-800.webp",
    "srcset": "/images/journal/thumbnails/string-theory-30cf6272-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/student-feedback.jpg": {
    "src": "/images/journal/thumbnails/student-feedback-b9cc3946-800.webp",
    "srcset": "/images/journal/thumbnails/student-feedback-b9cc3946-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/sustainability-systems-approach-with-scotch-college.jpg": {
    "src": "/images/journal/thumbnails/sustainability-systems-approach-with-scotch-college-8c78e7b2-800.webp",
    "srcset": "/images/journal/thumbnails/sustainability-systems-approach-with-scotch-college-8c78e7b2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/systems-thinking-at-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/systems-thinking-at-the-forktree-project-068e6476-800.webp",
    "srcset": "/images/journal/thumbnails/systems-thinking-at-the-forktree-project-068e6476-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/table-mountain.jpg": {
    "src": "/images/journal/thumbnails/table-mountain-84ab6875-800.webp",
    "srcset": "/images/journal/thumbnails/table-mountain-84ab6875-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/tabletastic.jpg": {
    "src": "/images/journal/thumbnails/tabletastic-69531e02-800.webp",
    "srcset": "/images/journal/thumbnails/tabletastic-69531e02-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/taking-a-stand-with-tree-guards.jpg": {
    "src": "/images/journal/thumbnails/taking-a-stand-with-tree-guards-229ddc2c-800.webp",
    "srcset": "/images/journal/thumbnails/taking-a-stand-with-tree-guards-229ddc2c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/taking-stock.jpg": {
    "src": "/images/journal/thumbnails/taking-stock-4cd46047-800.webp",
    "srcset": "/images/journal/thumbnails/taking-stock-4cd46047-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/tanktastic.jpg": {
    "src": "/images/journal/thumbnails/tanktastic-9215b192-800.webp",
    "srcset": "/images/journal/thumbnails/tanktastic-9215b192-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/tatachilla-outdoor-ed-on-the-case.jpg": {
    "src": "/images/journal/thumbnails/tatachilla-outdoor-ed-on-the-case-4f7c866c-800.webp",
    "srcset": "/images/journal/thumbnails/tatachilla-outdoor-ed-on-the-case-4f7c866c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/tatachilla-troopers.jpg": {
    "src": "/images/journal/thumbnails/tatachilla-troopers-324432d2-800.webp",
    "srcset": "/images/journal/thumbnails/tatachilla-troopers-324432d2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/teamwork-with-tatachilla-lutheran-college.jpeg": {
    "src": "/images/journal/thumbnails/teamwork-with-tatachilla-lutheran-college-96145148-800.webp",
    "srcset": "/images/journal/thumbnails/teamwork-with-tatachilla-lutheran-college-96145148-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/teamwork.jpg": {
    "src": "/images/journal/thumbnails/teamwork-bd3936dc-800.webp",
    "srcset": "/images/journal/thumbnails/teamwork-bd3936dc-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/technology-for-nature.jpg": {
    "src": "/images/journal/thumbnails/technology-for-nature-70a48d5c-800.webp",
    "srcset": "/images/journal/thumbnails/technology-for-nature-70a48d5c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/technology-for-sustainability.jpg": {
    "src": "/images/journal/thumbnails/technology-for-sustainability-3666d744-800.webp",
    "srcset": "/images/journal/thumbnails/technology-for-sustainability-3666d744-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/term-2-wrap-up.jpg": {
    "src": "/images/journal/thumbnails/term-2-wrap-up-a0d33864-800.webp",
    "srcset": "/images/journal/thumbnails/term-2-wrap-up-a0d33864-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/term-3-school-planting-round-up.jpg": {
    "src": "/images/journal/thumbnails/term-3-school-planting-round-up-9860933c-800.webp",
    "srcset": "/images/journal/thumbnails/term-3-school-planting-round-up-9860933c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/thank-you-trees-for-life-and-rotary.jpg": {
    "src": "/images/journal/thumbnails/thank-you-trees-for-life-and-rotary-1a109dd2-800.webp",
    "srcset": "/images/journal/thumbnails/thank-you-trees-for-life-and-rotary-1a109dd2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/thank-you-volunteers.jpg": {
    "src": "/images/journal/thumbnails/thank-you-volunteers-a259371e-800.webp",
    "srcset": "/images/journal/thumbnails/thank-you-volunteers-a259371e-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-first-windbreak-takes-shape.jpg": {
    "src": "/images/journal/thumbnails/the-first-windbreak-takes-shape-0fd4f2e5-800.webp",
    "srcset": "/images/journal/thumbnails/the-first-windbreak-takes-shape-0fd4f2e5-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-forktree-project-on-sbs-news.png": {
    "src": "/images/journal/thumbnails/the-forktree-project-on-sbs-news-490182ba-800.webp",
    "srcset": "/images/journal/thumbnails/the-forktree-project-on-sbs-news-490182ba-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-great-reveal.jpg": {
    "src": "/images/journal/thumbnails/the-great-reveal-64be41d3-800.webp",
    "srcset": "/images/journal/thumbnails/the-great-reveal-64be41d3-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-home-straight-for-planting-season-2024.jpg": {
    "src": "/images/journal/thumbnails/the-home-straight-for-planting-season-2024-f553c8b9-800.webp",
    "srcset": "/images/journal/thumbnails/the-home-straight-for-planting-season-2024-f553c8b9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-potential-of-tree-planting.jpg": {
    "src": "/images/journal/thumbnails/the-potential-of-tree-planting-e51dd3b0-800.webp",
    "srcset": "/images/journal/thumbnails/the-potential-of-tree-planting-e51dd3b0-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-power-of-collaboration-and-collective-purpose.jpg": {
    "src": "/images/journal/thumbnails/the-power-of-collaboration-and-collective-purpose-01eb2f78-800.webp",
    "srcset": "/images/journal/thumbnails/the-power-of-collaboration-and-collective-purpose-01eb2f78-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-power-of-team-days-at-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/the-power-of-team-days-at-the-forktree-project-47b2bc7e-800.webp",
    "srcset": "/images/journal/thumbnails/the-power-of-team-days-at-the-forktree-project-47b2bc7e-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-tatachilla-task-force-returns.jpg": {
    "src": "/images/journal/thumbnails/the-tatachilla-task-force-returns-be80152a-800.webp",
    "srcset": "/images/journal/thumbnails/the-tatachilla-task-force-returns-be80152a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/the-wonders-of-wallaby-grass.jpg": {
    "src": "/images/journal/thumbnails/the-wonders-of-wallaby-grass-6297854f-800.webp",
    "srcset": "/images/journal/thumbnails/the-wonders-of-wallaby-grass-6297854f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/thin-crust.jpg": {
    "src": "/images/journal/thumbnails/thin-crust-62b4068d-800.webp",
    "srcset": "/images/journal/thumbnails/thin-crust-62b4068d-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/thirsty-work.jpg": {
    "src": "/images/journal/thumbnails/thirsty-work-cef50491-800.webp",
    "srcset": "/images/journal/thumbnails/thirsty-work-cef50491-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/three-men-and-a-bobcat.jpg": {
    "src": "/images/journal/thumbnails/three-men-and-a-bobcat-7994c6ad-800.webp",
    "srcset": "/images/journal/thumbnails/three-men-and-a-bobcat-7994c6ad-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/timber-tops.jpg": {
    "src": "/images/journal/thumbnails/timber-tops-b229c7a7-800.webp",
    "srcset": "/images/journal/thumbnails/timber-tops-b229c7a7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/tintastic.jpg": {
    "src": "/images/journal/thumbnails/tintastic-283cccef-800.webp",
    "srcset": "/images/journal/thumbnails/tintastic-283cccef-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/top-deck.jpg": {
    "src": "/images/journal/thumbnails/top-deck-d499de0d-800.webp",
    "srcset": "/images/journal/thumbnails/top-deck-d499de0d-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/top-dressing.jpg": {
    "src": "/images/journal/thumbnails/top-dressing-9a59b39d-800.webp",
    "srcset": "/images/journal/thumbnails/top-dressing-9a59b39d-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/trees-are-more-important-now-than-ever-before.jpg": {
    "src": "/images/journal/thumbnails/trees-are-more-important-now-than-ever-before-29ecf079-800.webp",
    "srcset": "/images/journal/thumbnails/trees-are-more-important-now-than-ever-before-29ecf079-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/tymaline-building-services-come-on-board.jpg": {
    "src": "/images/journal/thumbnails/tymaline-building-services-come-on-board-8073d32b-800.webp",
    "srcset": "/images/journal/thumbnails/tymaline-building-services-come-on-board-8073d32b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/understorey-foundations.jpg": {
    "src": "/images/journal/thumbnails/understorey-foundations-f1e77728-800.webp",
    "srcset": "/images/journal/thumbnails/understorey-foundations-f1e77728-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/underwater-origins.jpg": {
    "src": "/images/journal/thumbnails/underwater-origins-c76ad771-800.webp",
    "srcset": "/images/journal/thumbnails/underwater-origins-c76ad771-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/upscaling-productivity.jpg": {
    "src": "/images/journal/thumbnails/upscaling-productivity-df1d150b-800.webp",
    "srcset": "/images/journal/thumbnails/upscaling-productivity-df1d150b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/urbanite.jpg": {
    "src": "/images/journal/thumbnails/urbanite-0ad5fa24-800.webp",
    "srcset": "/images/journal/thumbnails/urbanite-0ad5fa24-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/volunteer-force.jpg": {
    "src": "/images/journal/thumbnails/volunteer-force-39fa7029-800.webp",
    "srcset": "/images/journal/thumbnails/volunteer-force-39fa7029-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/war-of-the-weeds-returns.jpg": {
    "src": "/images/journal/thumbnails/war-of-the-weeds-returns-9ad88242-800.webp",
    "srcset": "/images/journal/thumbnails/war-of-the-weeds-returns-9ad88242-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/waste-not-want-not.jpg": {
    "src": "/images/journal/thumbnails/waste-not-want-not-585c1af2-800.webp",
    "srcset": "/images/journal/thumbnails/waste-not-want-not-585c1af2-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/water-ways.jpg": {
    "src": "/images/journal/thumbnails/water-ways-88c2da3b-800.webp",
    "srcset": "/images/journal/thumbnails/water-ways-88c2da3b-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/weather-wall.jpg": {
    "src": "/images/journal/thumbnails/weather-wall-bf5dc1f8-800.webp",
    "srcset": "/images/journal/thumbnails/weather-wall-bf5dc1f8-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/welcome-bush-heritage.jpg": {
    "src": "/images/journal/thumbnails/welcome-bush-heritage-eaf5250c-800.webp",
    "srcset": "/images/journal/thumbnails/welcome-bush-heritage-eaf5250c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/welcoming-the-clontarf-foundation-to-forktree.jpg": {
    "src": "/images/journal/thumbnails/welcoming-the-clontarf-foundation-to-forktree-d14c4f1c-800.webp",
    "srcset": "/images/journal/thumbnails/welcoming-the-clontarf-foundation-to-forktree-d14c4f1c-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/western-windbreak-completed.jpg": {
    "src": "/images/journal/thumbnails/western-windbreak-completed-efe622c9-800.webp",
    "srcset": "/images/journal/thumbnails/western-windbreak-completed-efe622c9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/whacky-races.jpg": {
    "src": "/images/journal/thumbnails/whacky-races-6d8e0a3f-800.webp",
    "srcset": "/images/journal/thumbnails/whacky-races-6d8e0a3f-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/whats-in-a-name.jpg": {
    "src": "/images/journal/thumbnails/whats-in-a-name-899567e6-800.webp",
    "srcset": "/images/journal/thumbnails/whats-in-a-name-899567e6-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/why-caring-for-the-planet-is-good-for-your-mental-health.jpg": {
    "src": "/images/journal/thumbnails/why-caring-for-the-planet-is-good-for-your-mental-health-f0c40551-800.webp",
    "srcset": "/images/journal/thumbnails/why-caring-for-the-planet-is-good-for-your-mental-health-f0c40551-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/wild-at-heart.jpg": {
    "src": "/images/journal/thumbnails/wild-at-heart-628f82d9-800.webp",
    "srcset": "/images/journal/thumbnails/wild-at-heart-628f82d9-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/winter-makeover-in-the-nursery.jpg": {
    "src": "/images/journal/thumbnails/winter-makeover-in-the-nursery-03967d65-800.webp",
    "srcset": "/images/journal/thumbnails/winter-makeover-in-the-nursery-03967d65-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/wired.jpg": {
    "src": "/images/journal/thumbnails/wired-6d9344fa-800.webp",
    "srcset": "/images/journal/thumbnails/wired-6d9344fa-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/working-conditions.jpg": {
    "src": "/images/journal/thumbnails/working-conditions-73c5d7a1-800.webp",
    "srcset": "/images/journal/thumbnails/working-conditions-73c5d7a1-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/working-with-the-fleurieu-swamp-restoration-network.jpg": {
    "src": "/images/journal/thumbnails/working-with-the-fleurieu-swamp-restoration-network-9610a7f0-800.webp",
    "srcset": "/images/journal/thumbnails/working-with-the-fleurieu-swamp-restoration-network-9610a7f0-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/world-environment-day-2025-at-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/world-environment-day-2025-at-the-forktree-project-9b3de142-800.webp",
    "srcset": "/images/journal/thumbnails/world-environment-day-2025-at-the-forktree-project-9b3de142-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/world-environment-day-at-the-forktree-project.jpg": {
    "src": "/images/journal/thumbnails/world-environment-day-at-the-forktree-project-6be82dd7-800.webp",
    "srcset": "/images/journal/thumbnails/world-environment-day-at-the-forktree-project-6be82dd7-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/wrapping-up-planting-season-2.jpg": {
    "src": "/images/journal/thumbnails/wrapping-up-planting-season-2-a987a6dc-800.webp",
    "srcset": "/images/journal/thumbnails/wrapping-up-planting-season-2-a987a6dc-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/zen-energy-boost.jpg": {
    "src": "/images/journal/thumbnails/zen-energy-boost-b938e72a-800.webp",
    "srcset": "/images/journal/thumbnails/zen-energy-boost-b938e72a-800.webp 800w",
    "width": 800,
    "height": 800
  },
  "/images/journal/zen-energy-power-boost-at-forktree.jpg": {
    "src": "/images/journal/thumbnails/zen-energy-power-boost-at-forktree-4349b7f0-800.webp",
    "srcset": "/images/journal/thumbnails/zen-energy-power-boost-at-forktree-4349b7f0-800.webp 800w",
    "width": 800,
    "height": 800
  }
} as const satisfies Record<string, JournalThumbnail>;

export function getJournalThumbnail(src?: string): JournalThumbnail | undefined {
  if (!src) return undefined;
  return journalThumbnails[src as keyof typeof journalThumbnails];
}

export function getJournalThumbnailSrc(src?: string): string | undefined {
  return getJournalThumbnail(src)?.src ?? src;
}
